Repository beyond-sw-camp/be08-fin-200OK-CONCENTRIC-backend, pull requests merged in 2024-11, with the labels that each got.

#182 [Docs] Update README.md
  README.md
Labels: Docs

#184 [Refactor/#179] cors 설정
  src/main/java/ok/backend/common/config/SecurityConfig.java
Labels: Backend, Refactoring

#185 [Refactor/#174] 하위 일정 로직 수정
  src/main/java/ok/backend/schedule/controller/SubScheduleController.java
  src/main/java/ok/backend/schedule/service/ScheduleService.java
  src/main/java/ok/backend/schedule/service/SubScheduleService.java
Labels: Backend, Refactoring

#190 [Refactor/#189] 팀 초대 로직 변경
  gradlew
  src/main/java/ok/backend/common/exception/ErrorCode.java
  src/main/java/ok/backend/member/controller/EmailController.java
  src/main/java/ok/backend/member/domain/entity/Invite.java
  src/main/java/ok/backend/member/domain/repository/InviteRepository.java
  src/main/java/ok/backend/member/service/EmailService.java
  src/main/java/ok/backend/member/service/InviteService.java
  src/main/java/ok/backend/team/controller/TeamController.java
  src/main/java/ok/backend/team/service/TeamSendingService.java
  src/main/java/ok/backend/team/service/TeamService.java
  src/test/java/ok/backend/team/service/TeamServiceTest.java
Labels: Backend, Refactoring

#193 [Feat] Workflow
  .github/workflows/backend.yml
Labels: Fix

#194 [Feat] Update backend.yml
  .github/workflows/backend.yml
Labels: Fix

#195 [Fix/#174] Dockerfile
  Dockerfile
Labels: Fix

#198 [Feat] 이번엔 진짜 함
  .github/workflows/backend.yml
Labels: Backend

#203 [Fix] Workflow 수정
  .github/workflows/backend.yml
Labels: Fix

#209 [Fix] 기도메타 on
  .github/workflows/backend.yml
Labels: Fix

#210 [Fix] 기도메타 2
  .github/workflows/backend.yml
Labels: Fix

#211 [Fix] ssh-action
  .github/workflows/backend.yml
Labels: Fix

#213 [Fix] 기도메타 3
  .github/workflows/backend.yml
Labels: Fix

#215 [Test] Workflow
  src/main/java/ok/backend/common/config/swagger/SwaggerConfig.java
Labels: Fix

#216 [Fix] workflow 코드 정리
  .github/workflows/backend.yml
Labels: Fix, Test

#218 [Fix] yaml update 수정
  .github/workflows/backend.yml
Labels: Fix

#219 [Fix] Update backend-deployment.yaml
  k8s/backend-deployment.yaml
Labels: Fix

#220 [Test] test
  src/main/java/ok/backend/common/config/swagger/SwaggerConfig.java
Labels: Fix, Test

#221 [Fix] update replicas
  k8s/backend-deployment.yaml
Labels: Frontend, Fix

#225 [Docs] cicd 기획서 수정, 웹후크 수정
  .github/cicd/README.md
  .github/workflows/backend.yml
Labels: Docs, Fix

#227 [Refactor/#226] wss 엔드포인트 변경
  src/main/java/ok/backend/common/config/SecurityConfig.java
  src/main/java/ok/backend/common/config/kafka/KafkaConstants.java
Labels: Backend, Refactoring

#228 [Refactor/#189] 팀 초대, 수락, 내보내기 로직 변경
  src/main/java/ok/backend/chat/service/ChatService.java
  src/main/java/ok/backend/common/config/SecurityConfig.java
  src/main/java/ok/backend/member/service/MemberService.java
  src/main/java/ok/backend/team/controller/TeamController.java
  src/main/java/ok/backend/team/dto/TeamInviteAcceptRequestDto.java
  src/main/java/ok/backend/team/service/TeamSendingService.java
  src/main/java/ok/backend/team/service/TeamService.java
Labels: Backend, Refactoring

#232 [Refactor/#229] 알림 기능 수정
  src/main/java/ok/backend/member/service/EmailService.java
  src/main/java/ok/backend/notification/controller/NotificationController.java
  src/main/java/ok/backend/notification/domain/entity/Notification.java
  src/main/java/ok/backend/notification/domain/entity/NotificationPending.java
  src/main/java/ok/backend/notification/domain/enums/NotificationType.java
  src/main/java/ok/backend/notification/dto/NotificationResponseDto.java
  src/main/java/ok/backend/notification/service/NotificationPendingService.java
  src/main/java/ok/backend/notification/service/NotificationService.java
  src/main/java/ok/backend/schedule/controller/ScheduleController.java
  src/main/java/ok/backend/schedule/controller/SubScheduleController.java
  src/main/java/ok/backend/schedule/service/ScheduleService.java
  src/main/java/ok/backend/schedule/service/SubScheduleService.java
  src/main/java/ok/backend/team/service/TeamService.java
Labels: Backend, Refactoring

#233 [Fix/#174] 팀 일정 불러오기 수정
  src/main/java/ok/backend/schedule/service/ScheduleService.java
Labels: Backend, Fix

#235 [Fix/#174] joinChat Test Fix
  src/test/java/ok/backend/chat/service/ChatServiceTest.java
Labels: Fix

#237 [Refactor/#229] 경로 수정
  src/main/java/ok/backend/team/service/TeamSendingService.java
Labels: Backend, Refactoring

#238 [Docs/#230] Update README.md
  README.md
Labels: Docs

#239 [refactor/#92] 이메일 폼 수정
  src/main/java/ok/backend/member/service/EmailService.java
Labels: Backend, Feat

#240 [Refactor/#229] 타임존 설정
  Dockerfile
Labels: Backend, Refactoring

#244 [Docs] 최종 readme
  README.md
Labels: Docs

#246 [Refactor/#245] 파일 다운로드
  src/main/java/ok/backend/common/config/SecurityConfig.java
Labels: Backend, Refactoring
